service:
    message:
        sample message from config server -update.
    value:
        Application configuration value 
    error:
        message:
            application error occurs
        description:
            Application has error in system

   
